name: CI
on:
  pull_request:

jobs:
  run:
    name: Run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('src/**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - uses: denoland/setup-deno@v1

      - run: deno cache --reload --unstable ./src/dep.ts

      - name: Post commit status
        run: |
          deno run \
            --allow-env \
            --allow-net \
            --allow-read \
            --unstable \
            src/index.ts \
            --context CI \
            --description "Post from CI" \
            --owner kektoncd \
            --repo github-commit-status \
            --sha ${{ github.event.pull_request.head.sha }} \
            --state success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
