name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  docker:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Get the version
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: true
          tags: 1915keke/github-commit-status:${{ steps.get-tag.outputs.tag }}

  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
